# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: com/beyoncloud/grpc/protos/dps_ocr/dps_ocr_to_infrence_service.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2


class DpsOcrInfServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetDpsOcrInfResponse(self, stream: 'grpclib.server.Stream[com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2.DpsOcrToInferenceRequest, com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2.DpsOcrToInferenceResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ocrinfrence.DpsOcrInfService/GetDpsOcrInfResponse': grpclib.const.Handler(
                self.GetDpsOcrInfResponse,
                grpclib.const.Cardinality.UNARY_UNARY,
                com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2.DpsOcrToInferenceRequest,
                com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2.DpsOcrToInferenceResponse,
            ),
        }


class DpsOcrInfServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetDpsOcrInfResponse = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ocrinfrence.DpsOcrInfService/GetDpsOcrInfResponse',
            com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2.DpsOcrToInferenceRequest,
            com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2.DpsOcrToInferenceResponse,
        )
