# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/beyoncloud/grpc/protos/dps_ocr/dps_ocr_to_infrence_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'com/beyoncloud/grpc/protos/dps_ocr/dps_ocr_to_infrence_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcom/beyoncloud/grpc/protos/dps_ocr/dps_ocr_to_infrence_service.proto\x12\x0bocrinfrence\"\x91\x03\n\x18\x44psOcrToInferenceRequest\x12\x1c\n\x14request_reference_id\x18\x01 \x01(\t\x12\x19\n\x11\x64ocument_batch_id\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x03 \x01(\x05\x12\x11\n\tdomain_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\x05\x12\x1b\n\x13\x64\x65sired_output_mode\x18\x06 \x01(\t\x12\x1d\n\x15\x64\x65sired_output_format\x18\x07 \x01(\t\x12\x18\n\x10source_file_path\x18\x08 \x01(\t\x12\x13\n\x0bsource_lang\x18\t \x01(\t\x12\x15\n\rdocument_type\x18\n \x01(\t\x12\x17\n\x0foutput_filename\x18\x0b \x01(\t\x12\x1f\n\x17ocr_result_storage_path\x18\x0c \x01(\t\x12%\n\x1dinference_result_storage_path\x18\r \x01(\t\x12\x1c\n\x14ocr_result_file_path\x18\x0e \x01(\t\"\xd7\x03\n\x19\x44psOcrToInferenceResponse\x12\x1c\n\x14request_reference_id\x18\x01 \x01(\t\x12\x19\n\x11\x64ocument_batch_id\x18\x02 \x01(\t\x12\x17\n\x0forganization_id\x18\x03 \x01(\x05\x12\x11\n\tdomain_id\x18\x04 \x01(\t\x12\x0f\n\x07user_id\x18\x05 \x01(\x05\x12\x1b\n\x13\x64\x65sired_output_mode\x18\x06 \x01(\t\x12\x1d\n\x15\x64\x65sired_output_format\x18\x07 \x01(\t\x12\x18\n\x10source_file_path\x18\x08 \x01(\t\x12\x13\n\x0bsource_lang\x18\t \x01(\t\x12\x15\n\rdocument_type\x18\n \x01(\t\x12\x17\n\x0foutput_filename\x18\x0b \x01(\t\x12\x1f\n\x17ocr_result_storage_path\x18\x0c \x01(\t\x12%\n\x1dinference_result_storage_path\x18\r \x01(\t\x12\x1c\n\x14ocr_result_file_path\x18\x0e \x01(\t\x12\"\n\x1ainference_result_file_path\x18\x0f \x01(\t\x12\x0e\n\x06status\x18\x10 \x01(\t\x12\x0f\n\x07message\x18\x11 \x01(\t2|\n\x10\x44psOcrInfService\x12h\n\x17get_dpsocr_inf_response\x12%.ocrinfrence.DpsOcrToInferenceRequest\x1a&.ocrinfrence.DpsOcrToInferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.beyoncloud.grpc.protos.dps_ocr.dps_ocr_to_infrence_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DPSOCRTOINFERENCEREQUEST']._serialized_start=86
  _globals['_DPSOCRTOINFERENCEREQUEST']._serialized_end=487
  _globals['_DPSOCRTOINFERENCERESPONSE']._serialized_start=490
  _globals['_DPSOCRTOINFERENCERESPONSE']._serialized_end=961
  _globals['_DPSOCRINFSERVICE']._serialized_start=963
  _globals['_DPSOCRINFSERVICE']._serialized_end=1087
# @@protoc_insertion_point(module_scope)
